# Generated by Django 5.0.6 on 2024-05-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_id'),
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_balance',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Requested', 'Requested'), ('Not Requested', 'Not Requested')], default='Not Requested', max_length=455),
        ),
    ]
